export const SERVER_URL = process.env.NEXT_PUBLIC_BACKEND_SERVER_URL;

export const ENDPOINT_ADMINS_ADMIN = process.env.NEXT_PUBLIC_ENDPOINT_ADMINS_ADMIN;
export const ENDPOINT_ADMINS_AUTH = process.env.NEXT_PUBLIC_ENDPOINT_ADMINS_AUTH;
export const ENDPOINT_ADMINS_CEO = process.env.NEXT_PUBLIC_ENDPOINT_ADMINS_CEO;
export const ENDPOINT_BELL = process.env.NEXT_PUBLIC_ENDPOINT_BELL;
export const ENDPOINT_BELL_ADMIN = process.env.NEXT_PUBLIC_ENDPOINT_BELL_ADMIN;

export const ENDPOINT_STOMP_DEFAULT = process.env.NEXT_PUBLIC_ENDPOINT_STOMP_DEFAULT;
export const ENDPOINT_BELL_STATUS_STOMP = process.env.NEXT_PUBLIC_ENDPOINT_BELL_STATUS_STOMP;
